### ISSUE TITLE
Breaks Help command (yes im sure its caused by dis plugin)

### ISSUE THREAD

**Issue by Moistcrafter** [hamusuke0323/DroppedItemsKiller#2]
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] emu.grasscutter.command.Command.usage() (Found data of type java.lang.String[killdroppeditems])
        at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:59)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
        at jdk.proxy2/jdk.proxy2.$Proxy6.usage(Unknown Source)
        at emu.grasscutter.command.CommandHandler.getUsageString(CommandHandler.java:58)
        at emu.grasscutter.command.commands.HelpCommand.createCommand(HelpCommand.java:22)
        at emu.grasscutter.command.commands.HelpCommand.lambda$execute$0(HelpCommand.java:56)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
        at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:53)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314)
        at emu.grasscutter.game.chat.ChatSystem.tryInvokeCommand(ChatSystem.java:46)
        at emu.grasscutter.game.chat.ChatSystem.sendPrivateMessage(ChatSystem.java:141)
        at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:18)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:93)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:222)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by hamusuke0323** [comment]
i got it, i will fix immediately

**Comment by hamusuke0323** [comment]
fixed
